# https://taskfile.dev
version: '3'

vars:
  ARGOCD_VERSION: "9.1.6"
  TF_DIR: terraform/timeweb
  KUBECONFIG_PATH: "{{.HOME}}/.kube/timeweb-config"

dotenv: ['.env']

env:
  KUBECONFIG: "{{.KUBECONFIG_PATH}}"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  # Infrastructure
  init:
    desc: "Initialize terraform and create cluster"
    cmds:
      - terraform -chdir={{.TF_DIR}} init
      - terraform -chdir={{.TF_DIR}} apply -auto-approve -refresh=true
      - task: kubeconfig

  refresh:
    desc: "Refresh Terraform outputs (after code changes)"
    cmds:
      - terraform -chdir={{.TF_DIR}} apply -refresh-only -auto-approve

  plan:
    desc: "Show terraform plan"
    cmds:
      - terraform -chdir={{.TF_DIR}} plan

  kubeconfig:
    desc: "Get kubeconfig from Terraform output"
    cmds:
      - mkdir -p {{.HOME}}/.kube
      - terraform -chdir={{.TF_DIR}} output -raw kubeconfig > {{.KUBECONFIG_PATH}}
      - chmod 600 {{.KUBECONFIG_PATH}}
      - echo "Kubeconfig saved to {{.KUBECONFIG_PATH}}"

  # ArgoCD Bootstrap
  bootstrap:
    desc: "Bootstrap ArgoCD in cluster"
    vars:
      HELM_CMD: >-
        helm template argocd argo/argo-cd
        --namespace argocd
        --version {{.ARGOCD_VERSION}}
        --values bootstrap/argocd/values.yaml
    cmds:
      - >-
        kubectl --kubeconfig={{.KUBECONFIG_PATH}}
        create namespace argocd --dry-run=client -o yaml |
        kubectl --kubeconfig={{.KUBECONFIG_PATH}} apply -f -
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - '{{.HELM_CMD}} | kubectl --kubeconfig={{.KUBECONFIG_PATH}} apply -f - || {{.HELM_CMD}} | kubectl --kubeconfig={{.KUBECONFIG_PATH}} apply -f -'

  argocd-password:
    desc: "Get ArgoCD admin password"
    cmds:
      - kubectl --kubeconfig={{.KUBECONFIG_PATH}} -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d && echo

  argocd-port-forward:
    desc: "Port-forward ArgoCD UI to localhost:8080"
    cmds:
      - kubectl --kubeconfig={{.KUBECONFIG_PATH}} port-forward svc/argocd-server -n argocd 8080:443

  # GitOps
  app-of-apps:
    desc: "Deploy root Application (app-of-apps)"
    cmds:
      - kubectl --kubeconfig={{.KUBECONFIG_PATH}} apply -f https://raw.githubusercontent.com/justgithubaccount/app-poly-gitops-k8s/main/platform/core/cluster-bootstrap/app-of-apps.yaml

  # Cleanup
  destroy:
    desc: "Destroy infrastructure (DANGER!)"
    prompt: "This will destroy all infrastructure. Are you sure?"
    cmds:
      - terraform -chdir={{.TF_DIR}} destroy -auto-approve

  # Full workflow
  up:
    desc: "Full setup: init + bootstrap + app-of-apps"
    cmds:
      - task: init
      - task: bootstrap
      - task: app-of-apps
      - task: argocd-password

  # === Diagnostics ===
  status:
    desc: "Check ArgoCD status (usage: task status -- [app-name])"
    cmds:
      - ./scripts/argocd-status.sh {{.CLI_ARGS}}

  sync-wait:
    desc: "Wait for ArgoCD app sync (usage: task sync-wait -- app-name)"
    cmds:
      - ./scripts/argocd-sync-check.sh {{.CLI_ARGS}}

  nodes:
    desc: "Check cluster nodes"
    cmds:
      - ./scripts/check-nodes.sh

  # === Secrets ===
  seal:
    desc: "Create SealedSecret (usage: task seal -- name namespace KEY=value)"
    cmds:
      - ./scripts/seal.sh {{.CLI_ARGS}}

  seal:openrouter:
    desc: "Create OpenRouter SealedSecret from .env"
    cmds:
      - ./scripts/seal.sh chat-openrouter chat-api OPENROUTER_API_KEY=$OPENROUTER_API_KEY

  seal:github:
    desc: "Create GitHub repo SealedSecret from .env"
    cmds:
      - ./scripts/seal.sh chat-github argocd --repo url=$GITHUB_REPO_URL username=$GITHUB_USERNAME password=$GITHUB_PAT

  seal:postgree:
    desc: "Create PostgreSQL SealedSecret from .env"
    cmds:
      - ./scripts/seal.sh chat-postgree chat-api DATABASE_URL=$DATABASE_URL
